In [6]:
import numpy as np
list_ = ['1','2','3','4','5']
array_list = np.array(object=list_)

yes there is a difference between datatypes

In [9]:
print("the data type of variables list_ is ",type(list_))
print("the data type of array_list is ",type(array_list))

the data type of variables list_ is  <class 'list'>
the data type of array_list is  <class 'numpy.ndarray'>


In [10]:
print("the data type of each elemet in variable list_ is ")
for i in list_ :
    print(type(i))
    
print("the data type of each element in array_list is ")
for i in array_list :
    print(type(i))

the data type of each elemet in variable list_ is 
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
the data type of each element in array_list is 
<class 'numpy.str_'>
<class 'numpy.str_'>
<class 'numpy.str_'>
<class 'numpy.str_'>
<class 'numpy.str_'>


In [11]:
array_list = np.array(object = list_, dtype = int)

Now, there is a difference between the datatype of elements 

In [15]:
print("the data type of each elemet in variable list_ is ")
for i in list_ :
    print(type(i))
    
print("the data type of each element in array_list is ")
for i in array_list :
    print(type(i))

the data type of each elemet in variable list_ is 
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
the data type of each element in array_list is 
<class 'numpy.int64'>
<class 'numpy.int64'>
<class 'numpy.int64'>
<class 'numpy.int64'>
<class 'numpy.int64'>


In [17]:
import numpy as np
num_list = [ [ 1 , 2 , 3 ] , [ 4 , 5 , 6 ] ]
num_array = np.array(object = num_list)

In [22]:
num_array

array([[1, 2, 3],
       [4, 5, 6]])

In [20]:
num_array.shape

(2, 3)

In [21]:
num_array.size

6

In [24]:
np.random.randint(0,1,(3,3))

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [29]:
np.diag([1,1,1,1,1])

array([[1, 0, 0, 0, 0],
       [0, 1, 0, 0, 0],
       [0, 0, 1, 0, 0],
       [0, 0, 0, 1, 0],
       [0, 0, 0, 0, 1]])